<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Title>Glory2Him.BibleProviders.ApiBible</Title>
		<Authors>Glory 2 Him</Authors>
		<Description>The ApiBible Bible Provider</Description>
		<Copyright>Copyright (c) 2025 Glory 2 Him</Copyright>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageIcon>Glory2Him-Square.png</PackageIcon>
		<Version>0.1.0.0</Version>
		<AssemblyVersion>0.1.0.0</AssemblyVersion>
		<FileVersion>0.1.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageProjectUrl>https://github.com/Glory2Him/Glory2Him.BibleProviders</PackageProjectUrl>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/Glory2Him/Glory2Him.BibleProviders.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>Glory 2 Him; G2H; C#; .NET; The Standard</PackageTags>
		<PackageReleaseNotes>
			Initial release of Glory2Him.BibleProviders.ApiBible
		</PackageReleaseNotes>
		<NoWarn>CS1998,CS8632</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</Content>
		<Content Include="README.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</Content>
		<Content Include="..\G2HSL.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</Content>
		<None Include="..\Resources\Images\Glory2Him-Banner.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\Resources\Images\Glory2Him-Square.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\Resources\Images\Glory2Him.ico">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Glory2Him.BibleProviders.Abstractions\Glory2Him.BibleProviders.Abstractions.csproj" />
	</ItemGroup>

</Project>
